### ISSUE TITLE
Adv vs Advanced

### ISSUE THREAD

**Issue by lhayhurst** [elistevens/xws-spec#21]
Hey - I got a lookup failure this morning from fabs that brings up a question I have for the group.

XWS spec has the advanced targetting computer with xws canonical as "advancedtargettingcomputer". this is what fabs is using.

Both voidstate and YASB are using 'advtargettingcomputer'.  

I'm cool either way, but dont want to start implementing multiple canon names in juggler :-)  Cheers!

**Comment by elistevens** [comment]
I say we go with the literal printing on the English card.

Since there's a ruling that says that "TIE Avd. Prototype" can't equip /x1
because it's not "TIE Advanced Prototype" I think it's important to use the
exact text.

It's a silly ruling, given how it messes up all of the "Raider Class Corv."
titles, but it's the ruling and we need to live with it for now.

**Comment by fab7431** [comment]
Hi all,
Ok, no problem to go with the printed american card names.

Eli, just let us know when the canonical names will be updated in the specs.
(in fact me as I think that I was the only one use "advanced" instead of "adv") ;-)))

**Comment by elistevens** [comment]
This will be addressed with XWS 1.0.0, which will be pushed momentarily. Please re-open if there are any remaining details to sort out.
