### ISSUE TITLE
New Poe Card Breaks XWS Format: Same Ship, Different Cost

### ISSUE THREAD

**Issue by voidstate** [elistevens/xws-spec#22]
I guess you guys have all seen this by now: https://images-cdn.fantasyflightgames.com/filer_public/20/17/2017500c-7dcd-44dc-b7e5-f73033d5edf5/swx57-poe-dameron.png

Leaving out how tricky it will be to implement in a squadron builder, how are we going to handle it in XWS? Currently, we assume that any ship/pilot combination is unique.

Ideas?

**Comment by voidstate** [comment]
And there's a new Millennium Falcon title. :(

**Comment by elistevens** [comment]
Yep.  :/

Okay, so the last time something like this came up in the spec (ordnance on
huge ship hardpoints), we kinda hit a wall where there were a lot of ideas
but no consensus emerged, and so things sorta stalled out. I'd like to
avoid that here. So unless someone has major objections, I'd like to just
declare what we're going to do by fiat.

Normalization for the majority of cards will be unchanged. When there is a
name collision, we'll use a more precise normalization, outlined below.

To determine collision for upgrades, simply see if there are two cards that
have the same canonicalized name.

To determine collision for pilots, see if there are pilots that for the
combination of (faction, ship, name) have the same canonicalized names.
Note that this doesn't use subfaction, since right now we only specify
faction at the list level, not the pilot level (since you can mix
subfactions in a single list).

Pilots and upgrades cannot collide with each other.

When there is a collision, then the canonicalized name becomes:

${name}-${upgrade slot}-${expansion product code}

milleniumfalcon-title-swx57
r2d2-crew-swx22

For pilots, we can skip the upgrade slot part:

poedameron-swx57

And if (jesus in heaven forbid) they decide to release two Kylo Ren pilots
in the same pack, then we tack on "a" "b" etc. with the ordering determined
first by increasing point cost, second by alphabetical card text if the
point costs are the same.

kyloren-swx58a
kyloren-swx58b

When a card appears in multiple expansion packs, we use the lowest numbered
expansion, unless FFG releases packs so far out of order that we've already
picked a canonicalization for a card before a lower swxNN shows up (seems
pretty unlikely).

It may seem like overkill now, but I think it will be worth it, both in
terms of readability of the JSON, and us not having to change the scheme
later. Again, this is only for cards with conflicts.

Doing it this way solves the hardpoint issue, since we'll no longer have
any confusion about if the upgrade equipped there is a different upgrade
type, since there's only one possible "clustermissile" upgrade; anything
with a conflict would be "clustermissile-hardpoint" or whatever. The JSON
would read "hardpoint": ["clustermissile"] and there's zero confusion about
what's going on.

It does mean that we're going to have to retroactively change the R2D2 Crew
canonicalization to "r2d2-crew-swx22" That sucks, but it needs to happen to
keep the future sane. Luke Skywalker doesn't need to change, since one's a
pilot, and one's an upgrade, and those cannot collide with one another.

Any objections?

**Comment by fab7431** [comment]
Hi all,

Just come back from theater watching Captain America Civil war, and I discover that !

I have just one point regarding the example about Kylo.
Perhaps we can go already this way even for pilots coming from different expansion but without mentionning the expansion ID.
Example for Poe : 
poedameron       (for Poe from SWX36 expansion)
poedameron_a    (for Poe from SWX57expansion)
or
poedameron         (for Poe from SWX36 expansion)
poedameron_2     (for Poe from SWX57expansion)

Perhaps everything will be more simple if we decide of one unique ID per card (upgrades and pilots)...

I don't have yet a clear idea, Eli if you could provide example for all the cases you describe, it will be great.

Thanks for your effort to try to solve this out.

**Comment by elistevens** [comment]
Hey Fab,

It's not clear what additional examples you're interested in. Can you
elaborate?

And note that what I'm proposing is, with the exceptions of upgrades and
pilots in different pools, and pilots moved to different ships/factions
(both legacy decisions that I don't think we should revisit at this point),
pretty much "one unique ID per card."

I don't like just tacking on "-2" because that makes it much less obvious
what's going on when looking at the JSON. "r2d2-crew-swx22" has pretty much
zero ambiguity.

Cheers,
Eli

**Comment by fab7431** [comment]
Just some xws examples to be sure that we have all the same understanding.
Regading this r2d2-crew-swx22, unfortunatly we cannot be certain that the same r2d2 crew card will not be released in an expansion pack about episode 8. And after that, how we will handle the following case: 
2 expansions with r2d2 crew as we know it today, and after ffg releases a new expansion with a new r2d2 crew card with a new ability...
It is unlikely for sure, but not completly impossible.

**Comment by elistevens** [comment]
Okay, so we'd have:

r2d2 (core set astromech, since it was the first and only at the time of
it's release)
r2d2-crew-swx22 (tantive crew, doesn't matter if they re-release it again)
r2d2-amd-swx66a (episode 8 whatever)
r2d2-amd-swx66b (episode 8 alternate version astro ability etc.)
r2d2-crew-swx66 (episode 8 crew version)
r2d2 (same swx66, but T-65 X-Wing pilot, since pilots and upgrades are
distinct)
r2s2-swx67 (now in a T-85 X-Wing)

Artoo gets around.

Does that answer your question?

**Comment by fab7431** [comment]
Indeed ;-)

**Comment by voidstate** [comment]
Wow. Great response, Eli. :)

However, I'm afraid I prefer Fab's idea: Just number versions after the first.

I still think it's unambiguous, it's simpler and is more easily human-writable. I think most people are more likely to know that "this is the 2nd version of Poe that was released" than "this is the version that was released in sxw57".

I also don't think we need to add the upgrade type to upgrades as they will already be in an array with a key of the upgrade type, eg. {"title":["millenniumfalcon"]} or {"title":["millenniumfalcon_2"]}

But, like you say, consensus is more important than details.

**Comment by guidokessels** [comment]
I don't have a strong preference either way. I prefer Eli's version but I can see how Fab's idea might be simpler to type.

**Comment by voidstate** [comment]
Come on then, Geordan... break the tie! :D

**Comment by geordanr** [comment]
Aw man, the pressure!

On the one hand, Fab's solution is shorter and easier to type, but Eli's is clearer and shouldn't require a centrally-managed lookup table (although we kind of have that going on now with abbreviations).

JSON is already a fairly verbose serialization format, so I don't think brevity is a concern.  I think I would lean toward the SKU-based format, which allows us to update XWS implementations without waiting for the XWS spec to formalize the canonicalization of a new card conflict.

Consider the case that FFG releases multiple preview articles within a short period of time, and a conflicting card appears in two of the articles.  One person might read the articles in a different order from another, and so there would be disagreement as to which card gets `card-1` vs `card-2` or whatever.  Tying it to SKU removes any change of ambiguity.

So that's my 2 cents~

**Comment by fab7431** [comment]
So, we can go with the SKU !

**Comment by voidstate** [comment]
SKU it it!

Can anyone explain why we need the upgrade type, though, re:

"I also don't think we need to add the upgrade type to upgrades as they will already be in an array with a key of the upgrade type, eg. {"title":["millenniumfalcon"]} or {"title":["millenniumfalcon_2"]}"

**Comment by fab7431** [comment]
I am with you on that, I don't see why we need the upgrade type.

**Comment by lhayhurst** [comment]
we've settled on poedameron-swx57, yeah? starting to implement these in listjuggler.

**Comment by lhayhurst** [comment]
sorry to spam. was there consensus on millenniumfalcon-swx57 versus millenniumfalcon-title-swx57? I don't care either way but if forced to chose would go with the first one (agree with fabs and fergus above)

**Comment by elistevens** [comment]
Okay, we can drop the -title- part, unless something like R2-D2 happens in
the same pack, but we can sort that out then.

**Comment by guidokessels** [comment]
Awesome! So the only existing card we need to change is R2D2 crew, which becomes `r2d2-swx22`?

**Comment by elistevens** [comment]
Seems right to me.

**Comment by elistevens** [comment]
This will be addressed with XWS 1.0.0, which will be pushed momentarily. Please re-open if there are any remaining details to sort out.

Note the README.md section on Sabine, since the data from YASB hasn't been matching what was described above (scum Sabine had -swx56, which doesn't match how we're handling scum Boba/Kath).

Let me know if we should drop the -swx56 (which is what the 1.0.0 spec will say), retroactively update scum Boba/Kath to include -swxNN, or make a permanent exception for those two, and have future pilots get the -swxNN across factions.

Personally, I go for the second one.

**Comment by elistevens** [comment]
Also, Hera should be `herasyndulla-swx39a` and  `herasyndulla-swx39b` depending on which ship she's in.

**Comment by fab7431** [comment]
Regarding Hera, for me there is no need to add -swx39a or -swx39n because the ships are different.

**Comment by elistevens** [comment]
You're right, Fab. That's what I get for trying to sort this out so late at night. I'll push an update to the spec.

I think that making any pilots that have the same name get a -swx suffix would be the cleanest overall (going back to Boba/Kath), but I think that backwards compatibility is more important here.

I'll push a tweak to the spec wording and README_NAMES.

However, YASB has some extra suffixes on Sabine and Maarek that we might need to address, if those have gotten into listjuggler, etc.

**Comment by lhayhurst** [comment]
they are in listjuggler, but it is an easy change. I'm cool with the solution discussed above!

**Comment by elistevens** [comment]
Let's pull the trigger on that then. I think that the current wording on the spec is consistent, but please let me know if there's a place that still needs attention.

I'll assume nobody needs a reminder ticket to update their projects, but let me know if one would help.

Closing this, since I think that we're done with the issues raised here.  Finally.  Sorry!
