### ISSUE TITLE
Support for Shield and Hull Values

### ISSUE THREAD

**Issue by kingargyle** [elistevens/xws-spec#23]
I'm working on a program for helping to manage Squads while a game is being streamed using either OBS or XSplit.   The purpose is to make it easier for the streamers to load and manage the squads, including remaining hull and shield values.   However, the XWS Spec includes everything about a ship, except for the amount of Hull or Shields it has.   While I realize that for most squad builders these values are in lookup tables, but for other programs it would be nice to have these values directly.

The fields can be optional, but it would be nice to have them there, so that if a squad builder supports it, it can export those values.

**Comment by sirjorj** [comment]
Heh.  I’m actually working some something like that too!
I have broken it into two parts - a library that just manages the core x-wing assets (with a sqlite db at the center of it) and a separate program that generates the images for the overlay.
The approach I took was to make the overlay generator have it’s own separate objects so I can add whatever else I need.
I am very much open to comparing notes - if we could combine our strengths for a better result, I would be in favor of that.

Jordon

**Comment by voidstate** [comment]
I do t think that this is the right place for that data. XWS is a format not a data set. What I mean is that XWS is really just some rules to standardise how to write out a squadron so that other apps can read it. 

I suggest you start another repo that contains ship stats and uses XWS for names so the ships can. We looked up in a standardised way. I reckon it could have a lot of uses. 

This is what I did for the X-Wing Card Images repo.

**Comment by voidstate** [comment]
https://github.com/voidstate/xwing-card-images

**Comment by Simon-HN** [comment]
You can find a regulary updated repo for stats here: https://github.com/guidokessels/xwing-data

**Comment by guidokessels** [comment]
Hah, I just started a streaming overlay project last week! Anyone want to collaborate and share code/notes?

I agree with voidstate that this repo probably isn't the right place for a data set.

As Simon-HN mentioned I have all card data and images available here: https://github.com/guidokessels/xwing-data. It has every card in the game, and each pilot and upgrade has the XWS id so you should be able to follow the XWS spec.

**Comment by kingargyle** [comment]
@guidokessels @sirjorj Probably need to take this off line from this particular issue, but you can find my project here.

https://github.com/kingargyle/xstreamer

@Simon-HN thanks I'll take a look at the xwing-data project.  I personally view xws as a data exchange format, but can understand where lookup tables may want to be kept separate.   I'll look at the xwing-card images and data projects.   Anybody else that may want to colaborate on the streaming overlay apps, feel free to look at what I started, it is by no means the best way to do it (I'm horrible at GUI design) especially in Java.

**Comment by elistevens** [comment]
I'm going to close this ticket, since it's out of scope for XWS.

However, I'm going to add a section to the bottom of the README with links to both XWS-compatible applications, and to other resources that developers might find useful, including everything linked here.

Please submit pull requests if there are additions, updates, or corrections etc. that should be made. Thanks!

**Comment by guidokessels** [comment]
Thanks @elistevens
